// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteArticle(arg1) {
  return window['go']['main']['App']['DeleteArticle'](arg1);
}

export function GetArticle(arg1) {
  return window['go']['main']['App']['GetArticle'](arg1);
}

export function GetCollectionStats() {
  return window['go']['main']['App']['GetCollectionStats']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetIndexingOverview() {
  return window['go']['main']['App']['GetIndexingOverview']();
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ImportArticle(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['ImportArticle'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ImportPDFBatch(arg1, arg2) {
  return window['go']['main']['App']['ImportPDFBatch'](arg1, arg2);
}

export function ListArticles() {
  return window['go']['main']['App']['ListArticles']();
}

export function ListSources() {
  return window['go']['main']['App']['ListSources']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function RunIndexingBenchmark() {
  return window['go']['main']['App']['RunIndexingBenchmark']();
}

export function SearchArticles(arg1) {
  return window['go']['main']['App']['SearchArticles'](arg1);
}

export function SearchBM25(arg1, arg2) {
  return window['go']['main']['App']['SearchBM25'](arg1, arg2);
}

export function SearchBM25Filtered(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SearchBM25Filtered'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SelectPDF() {
  return window['go']['main']['App']['SelectPDF']();
}

export function StartIndexing(arg1, arg2) {
  return window['go']['main']['App']['StartIndexing'](arg1, arg2);
}

export function UpdateArticle(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['UpdateArticle'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}
