// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function DeleteArticle(arg1:number):Promise<main.ActionResponse>;

export function GetArticle(arg1:number):Promise<main.ArticleDetailResponse>;

export function GetCollectionStats():Promise<models.CollectionStats>;

export function GetCurrentUser():Promise<models.User>;

export function GetIndexingOverview():Promise<models.IndexingOverview>;

export function Health():Promise<main.HealthResponse>;

export function ImportArticle(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<main.ActionResponse>;

export function ImportPDFBatch(arg1:number,arg2:string):Promise<main.BatchImportResponse>;

export function ListArticles():Promise<Array<models.ArticleSummary>>;

export function ListSources():Promise<Array<models.ArticleSource>>;

export function Login(arg1:string,arg2:string):Promise<main.AuthResponse>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<main.AuthResponse>;

export function RunIndexingBenchmark():Promise<main.BenchmarkResponse>;

export function SearchArticles(arg1:string):Promise<Array<models.ArticleSummary>>;

export function SearchBM25(arg1:string,arg2:number):Promise<Array<models.SearchResult>>;

export function SearchBM25Filtered(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:number):Promise<Array<models.SearchResult>>;

export function SelectPDF():Promise<main.FileSelectionResponse>;

export function StartIndexing(arg1:number,arg2:boolean):Promise<main.IndexingResponse>;

export function UpdateArticle(arg1:number,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string):Promise<main.ActionResponse>;
